name: Build

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The vcpkg repository to pull
        required: true
        default: https://github.com/microsoft/vcpkg.git
      branch:
        description: The vcpkg repository branch to pull
        required: true
        default: master
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        features: [gl, dawn, vulkan]
        include:
          - os: windows-latest
            features: direct3d
          - os: macos-latest
            features: metal
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Building skia[${{ matrix.features }}]
        shell: pwsh
        run: |
          ./vcpkg.ps1 -Repository ${{ github.event.inputs.repository }} -Branch ${{ github.event.inputs.branch }}
          ./vcpkg/vcpkg install skia[${{ matrix.features }}] --triplet ${{ matrix.triplet }}
