name: Build

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The vcpkg repository to pull
        required: true
        default: https://github.com/Juice-Labs/vcpkg.git
      branch:
        description: The vcpkg repository branch to pull
        required: true
        default: skia-update-internal
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        features: [gl, dawn, vulkan]
        include:
          - os: windows-latest
            features: direct3d
            triplet: x64-windows
          - os: macos-latest
            features: metal
            triplet: x64-osx
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: sudo apt install -y mesa-common-dev libx11-xcb-dev

      - name: Pulling ${{ github.event.inputs.repository }}
        shell: pwsh
        run: ./vcpkg.ps1 -Repository ${{ github.event.inputs.repository }} -Branch ${{ github.event.inputs.branch }}

      - name: Cache binary packages
        uses: actions/cache@v2
        with:
          path: ./vcpkg/archives
          key: ${{ matrix.os }}-vcpkg-archives-${{ matrix.features }}

      - name: Installing skia[${{ matrix.features }}]
        shell: bash
        run: |
          ./vcpkg/vcpkg install skia[${{ matrix.features }}] --triplet ${{ matrix.triplet }}

      - name: Archiving logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}-${{ matrix.features }}
          path: ./vcpkg/buildtrees/skia/*.log
